"""add_github_website_to_user

Revision ID: 4bc1723d0888
Revises: 0d58754ac4e6
Create Date: 2026-07-26 01:00:07.332733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bc1723d0888'
down_revision: Union[str, None] = '0d58754ac4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('github', sa.String(length=256), nullable=False))
    op.add_column('users', sa.Column('website', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website')
    op.drop_column('users', 'github')
    # ### end Alembic commands ###
