"""add_user_profile_fields

Revision ID: 0d58754ac4e6
Revises: 1190835d50a5
Create Date: 2026-07-25 18:32:11.815541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d58754ac4e6'
down_revision: Union[str, None] = '1190835d50a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(length=64), nullable=False))
    op.add_column('users', sa.Column('avatar', sa.String(length=512), nullable=False))
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'bio')
    op.drop_column('users', 'avatar')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
